server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:  ${PG_ADMIN_PASSWORD}
    url: jdbc:postgresql://localhost:5432/mvc_crud
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true